export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const FETCH_DATA_POST_PAGE = "FETCH_DATA_POST_PAGE";
export const FETCH_DATA_HOME_PAGE = "FETCH_DATA_HOME_PAGE";
export const FETCH_DATA_PROFILE_PAGE = "FETCH_DATA_PROFILE_PAGE";
